# Generated by Django 4.1.5 on 2023-03-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myskool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySkool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('caunt', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'MySkool',
                'verbose_name_plural': 'MySkool',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
