# Generated by Django 4.1.5 on 2023-03-12 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myskool', '0002_myskool_delete_mymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myskool',
            old_name='caunt',
            new_name='count',
        ),
    ]
