# Generated by Django 4.1.5 on 2023-03-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myskool', '0003_rename_caunt_myskool_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myskool',
            name='title',
        ),
        migrations.AddField(
            model_name='myskool',
            name='Age',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
