# Generated by Django 4.1.5 on 2023-03-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myskool', '0004_remove_myskool_title_myskool_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myskool',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='myskool',
            name='last_name',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
    ]
