# Generated by Django 4.1.5 on 2023-03-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myskool', '0005_rename_full_name_myskool_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myskool',
            old_name='count',
            new_name='Friday',
        ),
        migrations.AddField(
            model_name='myskool',
            name='Class_name',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myskool',
            name='Monday',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='myskool',
            name='Saturday',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='myskool',
            name='Sunday',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='myskool',
            name='Thursday',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='myskool',
            name='Tuesday',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='myskool',
            name='Wensday',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
