# Generated by Django 4.1.5 on 2023-03-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myskool', '0006_rename_count_myskool_friday_myskool_class_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myskool',
            name='Monthly',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='myskool',
            name='Weekly',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='myskool',
            name='Yearly',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
